# Generated by Django 4.0.4 on 2022-05-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_city_department_alter_department_country_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.notificationstatus'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.notificationtype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile'),
        ),
    ]
