# Generated by Django 4.0.4 on 2022-05-07 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_accounttransaction_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='ExpirationDate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 7, 3, 21, 56, 736813), null=True, verbose_name='Expire at'),
        ),
    ]
